dist: trusty
sudo: true
language: scala
services:
  - mongodb
scala:
  - 2.12.8
jdk:
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - e.shredinger@yahoo.com
    on_success: change
    on_failure: always

before_script: ./import-data.sh

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
#  - sbt ++$TRAVIS_SCALA_VERSION it:test //todo: fix later it tests!!!

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - pkill mongod
